# Generated by Django 3.0.8 on 2020-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200729_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pinned', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
