# Generated by Django 3.0.8 on 2020-07-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200714_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='C:\\Users\\Pedro\\Documents\\Repos\\hrchlhck\\portfolio\\simple_portfolio\\project_images'),
        ),
    ]
