# Generated by Django 3.0.8 on 2020-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200729_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pinned', 'name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
